(load "Exo3.rkt")

(let ((funcall-old funcall))
  (set! funcall (lambda (func args env)
                  (if (integer? func)
                      (let ((lst (car args)))
                        (when (not (list? lst))
                          (ms-error "integer selector argument must be a list"))
                        (let ((real-id (if (< func 0) (+ (length lst) func) func)))
                          (when (or (< real-id 0) (>= real-id (length lst)))
                            (ms-error "selector is out of bounds"))
                          (list-ref lst real-id)))
                      (funcall-old func args env)))))